displayName: Allow only Real IP from Cloudflare Proxy/Tunnel with LAN Whitelisting
type: middleware
import: github.com/YouKyi/cloudflarewarp
iconPath: .assets/icon.png

summary: resolve Cloudflare IPs, 403 blocks if non CF or Allowed IP is source 

testData:
  disableDefault: false
  trustip:
    - 2400:cb00::/32
